### ISSUE TITLE
CameraDrawer有一个设置水印的地方，如何去除水印？

### ISSUE THREAD

**Issue by weilei131** [qqchenjian318/VideoEditor-For-Android#19]
我在CameraDrawer这个类中有看到：
WaterMarkFilter waterMarkFilter = new WaterMarkFilter(resources);
        waterMarkFilter.setWaterMark(BitmapFactory.decodeResource(resources, R.mipmap.ic_launcher));
        waterMarkFilter.setPosition(30,50,0,0);
        addFilter(waterMarkFilter);
设置水印，但是注释后摄像头图像就上下颠倒了？如果不设置图片就会出现Null异常，感觉就是要设置一张图片的。这个水印应该怎么设置？

**Comment by weilei131** [comment]
把
WaterMarkFilter waterMarkFilter = new WaterMarkFilter(resources);
waterMarkFilter.setWaterMark(BitmapFactory.decodeResource(resources, R.mipmap.ic_launcher));
waterMarkFilter.setPosition(30,50,0,0);
addFilter(waterMarkFilter);
注释掉，然后使用 addFilter(showFilter);  //showFilter是CameraDrawer的一个全局变量。
再把
private void addFilter(AFilter filter) {
        /**抵消本身的颠倒操作*/
        filter.setMatrix(OM);
        mBeFilter.addFilter(filter);
    }
 filter.setMatrix(OM);一开始为注释状态，现在放开就行了，这样视频界面就不会颠倒了。

**Comment by zejiancai** [comment]
> addFilter(showFilter)

说的对，我也有需求，但自己做了，早知道看一下你的
