### ISSUE TITLE
求问 切换前置和后置摄像头的问题。感谢

### ISSUE THREAD

**Issue by youarenowhere** [qqchenjian318/VideoEditor-For-Android#30]
切换前置和后置摄像头的时候会有个上下颠倒切换的效果。能不能执行这个功能，但是不给前端用户显示出来。   现在切换的时候上下颠倒切换很明显。

**Comment by qqchenjian318** [comment]
其实这个问题可以通过跳视频帧即可解决，如果有切换摄像头，就跳过第一即可，功能我已经添加了
