### ISSUE TITLE
【请教】关于视频倒放，从原理上应该怎么做？

### ISSUE THREAD

**Issue by woniu0936** [qqchenjian318/VideoEditor-For-Android#31]
找不到你的邮箱，只能来这里提问了，如果有思路，麻烦指教指教

**Comment by qqchenjian318** [comment]
我没有做过，我能提供的思路就是 把原视频解码，然后对每一帧的时间戳进行处理，本来的时间戳说从0开始的，你可以从视频长度开始，然后再编码成新的视频，这样生成的视频应该就是倒放的，你可以尝试一下，但是好像Android的硬编码器，输入的视频时间戳好像必须递增。不然只有看看ffmpeg这个库有没有类似的方法

**Comment by woniu0936** [comment]
哦哦，好的，谢谢了 @qqchenjian318
