### ISSUE TITLE
添加滤镜合成视频的效率如何提升 

### ISSUE THREAD

**Issue by o03150** [qqchenjian318/VideoEditor-For-Android#38]
现在添加滤镜的合成时间,基本和视频源时长一样,有时甚至超过一点

**Comment by qqchenjian318** [comment]
已经是使用硬编码进行视频处理了，你可能需要看下流程上是否有可以优化的空间，如果你使用ffmpeg的软编码，比这还慢的多

**Comment by o03150** [comment]
能把解码放一个线程,编码放另一个线程吗
解码到surface,  surface底层好像是一个图像序列,应该在另一个线程编码应该不影响吧

**Comment by o03150** [comment]
大佬,流程上有什么优化思路吗?
