### ISSUE TITLE
下载demo就报错？请教一下

### ISSUE THREAD

**Issue by wangben5** [qqchenjian318/VideoEditor-For-Android#48]
![c7oc jef xuj25 l m8mus](https://user-images.githubusercontent.com/25680234/45995263-f2d7f980-c0c9-11e8-965e-7440bc1c6100.png)

**Comment by darkkillen** [comment]
replace this
`externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }`
with this
`externalNativeBuild {
            cmake {
                cppFlags ""
                abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
            }
        }`

**Comment by wangben5** [comment]
谢谢。

**Comment by qqchenjian318** [comment]
cmake相关设置，2楼已经给出了详细设置
